services:
  change-vol-ownership:
    image: alpine
    user: "root"
    group_add:
      - 1001
    volumes:
      - cache:/tmp/change-ownership
    command: chown -R 1001:1001 /tmp/change-ownership

  api:
    build: .
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - "cache:/var/cache/image-proxy:rw"
    user: "1001:1001"
    command:
      - node
      - /app/dist/index.js
      - --s3-bucket=my-bucket
      - --s3-endpoint=https://s3.example.com
      - --s3-region=eu-west-1
      - --cache-location=/var/cache/image-proxy
      - --origin=http://localhost:3000
    depends_on:
      change-vol-ownership:
        condition: service_completed_successfully

  proxy:
    build:
      context: nginx
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  cache: { }
